### ISSUE TITLE
https:// at the End of some URL in your Readme

### ISSUE THREAD

**Issue by MaxHambi** [sirredbeard/sirredbeard#1]
https://github.com/sirredbeard/sirredbeard/blob/9d2a417d493a89b56cd7e71433b62e922e98440f/README.md?plain=1#L61 https:// at the End of the [Rancher Labs]-URL 

https://github.com/sirredbeard/sirredbeard/blob/9d2a417d493a89b56cd7e71433b62e922e98440f/README.md?plain=1#L59 https:// at the End of the [Determined AI]-URL and [Pachyderm]-URL

https://github.com/sirredbeard/sirredbeard/blob/9d2a417d493a89b56cd7e71433b62e922e98440f/README.md?plain=1#L49 https:// at the End of the [Pengwin]-URL

https://github.com/sirredbeard/sirredbeard/blob/9d2a417d493a89b56cd7e71433b62e922e98440f/README.md?plain=1#L48 https:// at the End of the [wslinternals]-URL

https://github.com/sirredbeard/sirredbeard/blob/9d2a417d493a89b56cd7e71433b62e922e98440f/README.md?plain=1#L47 https:// at the End of the [Scoop]-URL

https://github.com/sirredbeard/sirredbeard/blob/9d2a417d493a89b56cd7e71433b62e922e98440f/README.md?plain=1#L45 https:// at the End of the [awesome-wsl]-URL and [awesome-unix]-URL 

https://github.com/sirredbeard/sirredbeard/blob/9d2a417d493a89b56cd7e71433b62e922e98440f/README.md?plain=1#L36 https:// at the End of the [books]-URL

https://github.com/sirredbeard/sirredbeard/blob/9d2a417d493a89b56cd7e71433b62e922e98440f/README.md?plain=1#L35 https:// at the End of the [blog]-URL

https://github.com/sirredbeard/sirredbeard/blob/9d2a417d493a89b56cd7e71433b62e922e98440f/README.md?plain=1#L31 https:// at the End of the [UNIX]-URL

Sooo i think that´s all of them.

**Comment by sirredbeard** [comment]
Thank you for bringing that to my attention @MaxHambi, very strange. I have fixed them. Thank you! I didn't think I needed a linter on my personal README.md, but I think I do!
